spring.application.name=central-api
server.port = 7071
db.api.url = http://localhost:7070/api/v1/db
notification.api.url = http://localhost:7072/api/v1/notify
gemini.token = AIzaSyBgyyZ6g8ltSx28NaSjd5hVA12nrYp_vlA
gemini.genai.url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
jwt.expiration.time = 1000000
jwt.secret.password = secretPassword